### ISSUE TITLE
gem ffi 1.9.21 known issue building on ubuntu 16.04 and others

### ISSUE THREAD

**Issue by WhiskeyTuesday** [thoughtbot/middleman-template#37]
See [here](https://github.com/ffi/ffi/issues/608) and [here](https://github.com/ffi/ffi/issues/607) for reference.

the ffi gem which is somewhere in the dependency tree is broken at this version. I don't know which dependency tree it's in or how to find out, but the version of something which hopefully you guys control should probably be incremented.

**Comment by tysongach** [comment]
We just made this project a [Middleman Project Template](https://middlemanapp.com/advanced/project-templates/) (see #40), and by doing that we no longer check in the `Gemfile.lock` into this repo. That should mean this issue is no longer relevant because the ffi gem is not a first-class dependency of this project, and the installing of all gem dependencies now happens when you run the Middleman CLI to start a new app with this template.
